---
port: '8080'

max_distance_grab: 64

time_preparation: 15.0
time_finish: 20.0
time_between: 2.0
number_rounds: 2
players_allowed: 10

TIME_BOMB_EXPLOTE: 15
TIME_BOMB_ACTIVATE: 5
TIME_BOMB_DEACTIVATE: 5

stencil_angle: 60
stencil_radio: 64
alpha_blending: 150

character_life_points: 100
bonus_kill: 15
end_round_bonification: 20
win_round_bonification: 50

character_money: 500


glock_accuracy: 1.0
ak47_accuracy: 0.7
m3_accuracy: 0.3
awp_accuracy: 1.0

knife_damage_min: 5.0
glock_damage_min: 7.0
ak47_damage_min: 10.0
m3_damage_min: 3.0
awp_damage_min: 30.0

knife_damage_max: 8.0
glock_damage_max: 10.0
ak47_damage_max: 15.0
m3_damage_max: 5.0
awp_damage_max: 50.0

ak47_shoot_rate: 3
ak47_shoot_freq: 0.4


glock_distance_penalty: 0.02
ak47_distance_penalty: 0.01
m3_distance_penalty: 0.03
awp_distance_penalty: 0
knife_distance_penalty: 0

glock_ammo: 20
ak47_ammo: 30
m3_ammo: 8
awp_ammo: 10

glock_max_ammo: 120
ak47_max_ammo: 90
m3_max_ammo: 32
awp_max_ammo: 30

ak47_price: 250
m3_price: 170
awp_price: 475

ak47_10_bullets_price: 50
m3_10_bullets_price: 30
awp_10_bullets_price: 35
glock_10_bullets_price: 40

glock_max_distance: 384.0
ak47_max_distance: 640.0
m3_max_distance: 256.0
awp_max_distance: 768.0
knife_max_distance: 20.0

awp_retard_time: 1.0
m3_angle_covered: 60
