---
max_distance_grab: 64

time_preparation: 5
time_finish: 20
time_between: 2
number_rounds: 10
players_allowed: 10
velocity_iterations: 8
position_iterations: 3

TIME_BOMB_EXPLOTE: 15
TIME_BOMB_ACTIVATE: 5
TIME_BOMB_DEACTIVATE: 5


character_life_points: 100
bonus_kill: 50

character_money: 100

glock_accuracy: 0.8
ak47_accuracy: 0.8
m3_accuracy: 0.7
awp_accuracy: 0.9

knife_damage_min: 5.0
glock_damage_min: 7.0
ak47_damage_min: 10.0
m3_damage_min: 15.0
awp_damage_min: 30.0

knife_damage_max: 8.0
glock_damage_max: 10.0
ak47_damage_max: 15.0
m3_damage_max: 20.0
awp_damage_max: 50.0

ak47_shoot_rate: 3
ak47_shoot_freq: 0.4


glock_distance_penalty: 0.02
ak47_distance_penalty: 0.01
m3_distance_penalty: 0.03
awp_distance_penalty: 0
knife_distance_penalty: 0

glock_ammo: 50
ak47_ammo: 120
m3_ammo: 90
awp_ammo: 20

glock_price: 15
ak47_price: 30
m3_price: 50
awp_price: 100

glock_max_distance: 80.0
ak47_max_distance: 100.0
m3_max_distance: 50.0
awp_max_distance: 768.0
knife_max_distance: 40.0

awp_retard_time: 2
