width: 5
height: 4
---
node: 0
item: base_inferno
position:
  - 1
  - 3
---
node: 1
item: base_inferno
position:
  - 2
  - 3
---
node: 2
item: base_inferno
position:
  - 0
  - 3
---
node: 3
item: base_inferno
position:
  - 1
  - 2
---
node: 4
item: base_inferno
position:
  - 2
  - 2
---
node: 5
item: base_inferno
position:
  - 0
  - 2
---
node: 6
item: base_inferno
position:
  - 4
  - 2
---
node: 7
item: base_inferno
position:
  - 3
  - 2
---
node: 8
item: base_inferno
position:
  - 0
  - 1
---
node: 9
item: base_inferno
position:
  - 2
  - 0
---
node: 10
item: base_inferno
position:
  - 0
  - 0
---
node: 11
item: base_inferno
position:
  - 1
  - 0
---
node: 12
item: base_inferno
position:
  - 1
  - 1
---
node: 13
item: base_inferno
position:
  - 3
  - 1
---
node: 14
item: base_inferno
position:
  - 3
  - 0
---
node: 15
item: base_inferno
position:
  - 2
  - 1
---
node: 16
item: base_inferno
position:
  - 4
  - 1
---
node: 17
item: base_inferno
position:
  - 4
  - 0
---
node: 0
item: C_spawn
position:
  - 4
  - 2
---
node: 1
item: C_spawn
position:
  - 0
  - 3
---
node: 2
item: T_spawn
position:
  - 1
  - 0
---
node: 3
item: T_spawn
position:
  - 0
  - 0