width: 5
height: 4
---
node: 0
item: base_inferno
position:
  - 4
  - 0
---
node: 1
item: base_inferno
position:
  - 4
  - 1
---
position:
  - 2
  - 1
item: base_inferno
node: 2
---
item: base_inferno
position:
  - 3
  - 0
node: 3
---
node: 4
position:
  - 3
  - 1
item: base_inferno
---
position:
  - 1
  - 1
item: base_inferno
node: 5
---
node: 6
position:
  - 1
  - 0
item: base_inferno
---
item: base_inferno
position:
  - 0
  - 0
node: 7
---
node: 8
item: base_inferno
position:
  - 2
  - 0
---
position:
  - 0
  - 1
node: 9
item: base_inferno
---
node: 10
item: base_inferno
position:
  - 3
  - 2
---
node: 11
item: base_inferno
position:
  - 4
  - 2
---
node: 12
item: base_inferno
position:
  - 0
  - 2
---
item: base_inferno
position:
  - 2
  - 2
node: 13
---
item: base_inferno
position:
  - 1
  - 2
node: 14
---
item: base_inferno
position:
  - 0
  - 3
node: 15
---
item: base_inferno
position:
  - 2
  - 3
node: 16
---
position:
  - 1
  - 3
item: base_inferno
node: 17
---
position:
  - 0
  - 0
item: T_spawn
node: 0
---
position:
  - 1
  - 0
node: 1
item: T_spawn
---
item: C_spawn
node: 2
position:
  - 0
  - 3
---
node: 3
item: C_spawn
position:
  - 4
  - 2