width: 9
height: 5
---
position:
  - 4
  - 0
item: base_aztec
---
item: base_aztec
position:
  - 3
  - 0
---
item: base_aztec
position:
  - 7
  - 0
---
item: base_aztec
position:
  - 1
  - 0
---
position:
  - 2
  - 0
item: base_aztec
---
item: base_aztec
position:
  - 6
  - 0
---
item: base_aztec
position:
  - 4
  - 1
---
item: base_aztec
position:
  - 8
  - 0
---
item: base_aztec
position:
  - 5
  - 0
---
position:
  - 6
  - 1
item: base_aztec
---
position:
  - 7
  - 1
item: base_aztec
---
item: base_aztec
position:
  - 8
  - 1
---
item: base_aztec
position:
  - 2
  - 1
---
item: base_aztec
position:
  - 5
  - 1
---
item: base_aztec
position:
  - 3
  - 1
---
item: base_aztec
position:
  - 0
  - 0
---
position:
  - 1
  - 1
item: base_aztec
---
item: base_aztec
position:
  - 0
  - 1
---
item: base_aztec
position:
  - 8
  - 2
---
item: base_aztec
position:
  - 8
  - 3
---
item: base_aztec
position:
  - 8
  - 4
---
item: base_aztec
position:
  - 0
  - 2
---
item: base_aztec
position:
  - 0
  - 3
---
item: base_aztec
position:
  - 0
  - 4
---
position:
  - 1
  - 4
item: base_aztec
---
position:
  - 2
  - 4
item: base_inferno
---
position:
  - 3
  - 4
item: base_aztec
---
item: base_aztec
position:
  - 4
  - 4
---
item: base_aztec
position:
  - 5
  - 4
---
item: base_aztec
position:
  - 6
  - 4
---
item: base_aztec
position:
  - 7
  - 4
---
position:
  - 1
  - 2
item: base_aztec
---
item: base_aztec
position:
  - 1
  - 3
---
item: base_aztec
position:
  - 2
  - 2
---
item: base_aztec
position:
  - 2
  - 3
---
position:
  - 3
  - 2
item: base_aztec
---
position:
  - 3
  - 3
item: base_aztec
---
position:
  - 4
  - 2
item: base_aztec
---
position:
  - 4
  - 3
item: base_aztec
---
item: base_aztec
position:
  - 5
  - 3
---
item: base_aztec
position:
  - 5
  - 2
---
item: base_aztec
position:
  - 6
  - 3
---
position:
  - 6
  - 2
item: base_aztec
---
item: base_aztec
position:
  - 7
  - 2
---
position:
  - 7
  - 3
item: base_aztec
---
item: T_spawn
position:
  - 0
  - 0
---
item: T_spawn
position:
  - 0
  - 1
---
position:
  - 0
  - 2
item: T_spawn
---
item: T_spawn
position:
  - 0
  - 3
---
item: T_spawn
position:
  - 0
  - 4
---
item: C_spawn
position:
  - 8
  - 0
---
position:
  - 8
  - 1
item: C_spawn
---
position:
  - 8
  - 2
item: C_spawn
---
position:
  - 8
  - 3
item: C_spawn
---
item: C_spawn
position:
  - 8
  - 4