width: 9
height: 5
---
position:
  - 4
  - 0
node: 0
item: base_aztec
---
item: base_aztec
position:
  - 3
  - 0
node: 1
---
node: 2
item: base_aztec
position:
  - 7
  - 0
---
item: base_aztec
node: 3
position:
  - 1
  - 0
---
position:
  - 2
  - 0
item: base_aztec
node: 4
---
item: base_aztec
position:
  - 6
  - 0
node: 5
---
item: base_aztec
node: 6
position:
  - 4
  - 1
---
node: 7
item: base_aztec
position:
  - 8
  - 0
---
item: base_aztec
position:
  - 5
  - 0
node: 8
---
position:
  - 6
  - 1
node: 9
item: base_aztec
---
position:
  - 7
  - 1
node: 10
item: base_aztec
---
item: base_aztec
position:
  - 8
  - 1
node: 11
---
item: base_aztec
node: 12
position:
  - 2
  - 1
---
item: base_aztec
position:
  - 5
  - 1
node: 13
---
node: 14
item: base_aztec
position:
  - 3
  - 1
---
item: base_aztec
position:
  - 0
  - 0
node: 15
---
position:
  - 1
  - 1
node: 16
item: base_aztec
---
item: base_aztec
position:
  - 0
  - 1
node: 17
---
node: 18
item: base_aztec
position:
  - 8
  - 2
---
item: base_aztec
position:
  - 8
  - 3
node: 19
---
node: 20
item: base_aztec
position:
  - 8
  - 4
---
item: base_aztec
node: 21
position:
  - 0
  - 2
---
item: base_aztec
node: 22
position:
  - 0
  - 3
---
item: base_aztec
position:
  - 0
  - 4
node: 23
---
position:
  - 1
  - 4
node: 24
item: base_aztec
---
position:
  - 2
  - 4
item: base_inferno
node: 25
---
position:
  - 3
  - 4
node: 26
item: base_aztec
---
node: 27
item: base_aztec
position:
  - 4
  - 4
---
item: base_aztec
position:
  - 5
  - 4
node: 28
---
item: base_aztec
position:
  - 6
  - 4
node: 29
---
node: 30
item: base_aztec
position:
  - 7
  - 4
---
position:
  - 1
  - 2
item: base_aztec
node: 31
---
item: base_aztec
node: 32
position:
  - 1
  - 3
---
item: base_aztec
position:
  - 2
  - 2
node: 33
---
item: base_aztec
node: 34
position:
  - 2
  - 3
---
node: 35
position:
  - 3
  - 2
item: base_aztec
---
position:
  - 3
  - 3
item: base_aztec
node: 36
---
position:
  - 4
  - 2
node: 37
item: base_aztec
---
position:
  - 4
  - 3
item: base_aztec
node: 38
---
item: base_aztec
position:
  - 5
  - 3
node: 39
---
node: 40
item: base_aztec
position:
  - 5
  - 2
---
node: 41
item: base_aztec
position:
  - 6
  - 3
---
position:
  - 6
  - 2
item: base_aztec
node: 42
---
item: base_aztec
position:
  - 7
  - 2
node: 43
---
position:
  - 7
  - 3
item: base_aztec
node: 44
---
node: 0
item: T_spawn
position:
  - 0
  - 0
---
node: 1
item: T_spawn
position:
  - 0
  - 1
---
position:
  - 0
  - 2
node: 2
item: T_spawn
---
node: 3
item: T_spawn
position:
  - 0
  - 3
---
item: T_spawn
node: 4
position:
  - 0
  - 4
---
item: C_spawn
position:
  - 8
  - 0
node: 5
---
position:
  - 8
  - 1
node: 6
item: C_spawn
---
position:
  - 8
  - 2
node: 7
item: C_spawn
---
position:
  - 8
  - 3
item: C_spawn
node: 8
---
node: 9
item: C_spawn
position:
  - 8
  - 4