width: 283796062672454641
height: 5
---
node: 0
item: base_aztec
position:
  - 7
  - 3
---
node: 1
item: base_aztec
position:
  - 7
  - 2
---
node: 2
item: base_aztec
position:
  - 6
  - 2
---
node: 3
item: base_aztec
position:
  - 6
  - 3
---
node: 4
item: base_aztec
position:
  - 5
  - 2
---
node: 5
item: base_aztec
position:
  - 5
  - 3
---
node: 6
item: base_aztec
position:
  - 4
  - 3
---
node: 7
item: base_aztec
position:
  - 4
  - 2
---
node: 8
item: base_aztec
position:
  - 3
  - 3
---
node: 9
item: base_aztec
position:
  - 3
  - 2
---
node: 10
item: base_aztec
position:
  - 2
  - 3
---
node: 11
item: base_aztec
position:
  - 2
  - 2
---
node: 12
item: base_aztec
position:
  - 1
  - 3
---
node: 13
item: base_aztec
position:
  - 1
  - 2
---
node: 14
item: base_aztec
position:
  - 7
  - 4
---
node: 15
item: base_aztec
position:
  - 6
  - 4
---
node: 16
item: base_aztec
position:
  - 5
  - 4
---
node: 17
item: base_aztec
position:
  - 4
  - 4
---
node: 18
item: base_aztec
position:
  - 3
  - 4
---
node: 19
item: base_inferno
position:
  - 2
  - 4
---
node: 20
item: base_aztec
position:
  - 1
  - 4
---
node: 21
item: base_aztec
position:
  - 0
  - 4
---
node: 22
item: base_aztec
position:
  - 0
  - 3
---
node: 23
item: base_aztec
position:
  - 0
  - 2
---
node: 24
item: base_aztec
position:
  - 8
  - 4
---
node: 25
item: base_aztec
position:
  - 8
  - 3
---
node: 26
item: base_aztec
position:
  - 8
  - 2
---
node: 27
item: base_aztec
position:
  - 0
  - 1
---
node: 28
item: base_aztec
position:
  - 1
  - 1
---
node: 29
item: base_aztec
position:
  - 0
  - 0
---
node: 30
item: base_aztec
position:
  - 3
  - 1
---
node: 31
item: base_aztec
position:
  - 5
  - 1
---
node: 32
item: base_aztec
position:
  - 2
  - 1
---
node: 33
item: base_aztec
position:
  - 8
  - 1
---
node: 34
item: base_aztec
position:
  - 7
  - 1
---
node: 35
item: base_aztec
position:
  - 6
  - 1
---
node: 36
item: base_aztec
position:
  - 5
  - 0
---
node: 37
item: base_aztec
position:
  - 8
  - 0
---
node: 38
item: base_aztec
position:
  - 4
  - 1
---
node: 39
item: base_aztec
position:
  - 6
  - 0
---
node: 40
item: base_aztec
position:
  - 2
  - 0
---
node: 41
item: base_aztec
position:
  - 1
  - 0
---
node: 42
item: base_aztec
position:
  - 7
  - 0
---
node: 43
item: base_aztec
position:
  - 3
  - 0
---
node: 44
item: base_aztec
position:
  - 4
  - 0
---
node: 0
item: bomb_area_a
position:
  - 4
  - 2
---
node: 1
item: m3_weapon
position:
  - 2
  - 4
---
node: 2
item: box_black
position:
  - 2
  - 0
---
node: 3
item: box_black
position:
  - 6
  - 4
---
node: 4
item: box_wood_metal
position:
  - 2
  - 2
---
node: 5
item: box_metal
position:
  - 4
  - 3
---
node: 6
item: box_brown
position:
  - 5
  - 0
---
node: 7
item: awp_weapon
position:
  - 3
  - 2
---
node: 8
item: ak47_weapon
position:
  - 5
  - 1
---
node: 9
item: glock_weapon
position:
  - 3
  - 0
---
node: 10
item: C_spawn
position:
  - 8
  - 4
---
node: 11
item: C_spawn
position:
  - 8
  - 3
---
node: 12
item: C_spawn
position:
  - 8
  - 2
---
node: 13
item: C_spawn
position:
  - 8
  - 1
---
node: 14
item: C_spawn
position:
  - 8
  - 0
---
node: 15
item: T_spawn
position:
  - 0
  - 4
---
node: 16
item: T_spawn
position:
  - 0
  - 3
---
node: 17
item: T_spawn
position:
  - 0
  - 2
---
node: 18
item: T_spawn
position:
  - 0
  - 1
---
node: 19
item: T_spawn
position:
  - 0
  - 0