height: 5
width: 9
---
position:
  - 4
  - 0
node: 0
item: base_aztec
---
item: base_aztec
position:
  - 3
  - 0
node: 1
---
node: 2
item: base_aztec
position:
  - 7
  - 0
---
node: 3
position:
  - 1
  - 0
item: base_aztec
---
position:
  - 2
  - 0
node: 4
item: base_aztec
---
position:
  - 6
  - 0
node: 5
item: base_aztec
---
node: 6
position:
  - 4
  - 1
item: base_aztec
---
node: 7
item: base_aztec
position:
  - 8
  - 0
---
position:
  - 5
  - 0
item: base_aztec
node: 8
---
node: 9
position:
  - 6
  - 1
item: base_aztec
---
position:
  - 7
  - 1
item: base_aztec
node: 10
---
item: base_aztec
position:
  - 8
  - 1
node: 11
---
position:
  - 2
  - 1
item: base_aztec
node: 12
---
node: 13
position:
  - 5
  - 1
item: base_aztec
---
node: 14
item: base_aztec
position:
  - 3
  - 1
---
item: base_aztec
position:
  - 0
  - 0
node: 15
---
position:
  - 1
  - 1
item: base_aztec
node: 16
---
item: base_aztec
node: 17
position:
  - 0
  - 1
---
item: base_aztec
position:
  - 8
  - 2
node: 18
---
node: 19
item: base_aztec
position:
  - 8
  - 3
---
item: base_aztec
position:
  - 8
  - 4
node: 20
---
node: 21
position:
  - 0
  - 2
item: base_aztec
---
position:
  - 0
  - 3
item: base_aztec
node: 22
---
position:
  - 0
  - 4
node: 23
item: base_aztec
---
node: 24
item: base_aztec
position:
  - 1
  - 4
---
node: 25
item: base_inferno
position:
  - 2
  - 4
---
item: base_aztec
node: 26
position:
  - 3
  - 4
---
item: base_aztec
position:
  - 4
  - 4
node: 27
---
position:
  - 5
  - 4
item: base_aztec
node: 28
---
item: base_aztec
position:
  - 6
  - 4
node: 29
---
position:
  - 7
  - 4
node: 30
item: base_aztec
---
item: base_aztec
position:
  - 1
  - 2
node: 31
---
item: base_aztec
node: 32
position:
  - 1
  - 3
---
node: 33
item: base_aztec
position:
  - 2
  - 2
---
node: 34
item: base_aztec
position:
  - 2
  - 3
---
item: base_aztec
position:
  - 3
  - 2
node: 35
---
position:
  - 3
  - 3
item: base_aztec
node: 36
---
position:
  - 4
  - 2
node: 37
item: base_aztec
---
node: 38
item: base_aztec
position:
  - 4
  - 3
---
node: 39
item: base_aztec
position:
  - 5
  - 3
---
item: base_aztec
position:
  - 5
  - 2
node: 40
---
item: base_aztec
position:
  - 6
  - 3
node: 41
---
node: 42
item: base_aztec
position:
  - 6
  - 2
---
item: base_aztec
node: 43
position:
  - 7
  - 2
---
node: 44
position:
  - 7
  - 3
item: base_aztec
---
item: base_inferno
position:
  - 4
  - 1
node: 45
---
item: base_inferno
node: 46
position:
  - 2
  - 1
---
node: 47
item: base_inferno
position:
  - 3
  - 0
---
item: base_inferno
position:
  - 3
  - 1
node: 48
---
item: base_inferno
position:
  - 1
  - 1
node: 49
---
position:
  - 1
  - 0
node: 50
item: base_inferno
---
position:
  - 0
  - 0
node: 51
item: base_inferno
---
item: base_inferno
position:
  - 2
  - 0
node: 52
---
item: base_inferno
node: 53
position:
  - 0
  - 1
---
position:
  - 3
  - 2
item: base_inferno
node: 54
---
item: base_inferno
position:
  - 4
  - 2
node: 55
---
position:
  - 0
  - 2
node: 56
item: base_inferno
---
item: base_inferno
node: 57
position:
  - 2
  - 2
---
node: 58
item: base_inferno
position:
  - 1
  - 2
---
item: base_inferno
position:
  - 0
  - 3
node: 59
---
item: base_inferno
position:
  - 2
  - 3
node: 60
---
node: 61
item: base_inferno
position:
  - 1
  - 3
---
item: T_spawn
position:
  - 0
  - 0
node: 0
---
item: T_spawn
node: 1
position:
  - 0
  - 1
---
node: 2
position:
  - 0
  - 2
item: T_spawn
---
item: T_spawn
node: 3
position:
  - 0
  - 3
---
position:
  - 0
  - 4
item: T_spawn
node: 4
---
item: C_spawn
node: 5
position:
  - 8
  - 0
---
position:
  - 8
  - 1
item: C_spawn
node: 6
---
node: 7
position:
  - 8
  - 2
item: C_spawn
---
item: C_spawn
node: 8
position:
  - 8
  - 3
---
item: C_spawn
position:
  - 8
  - 4
node: 9
---
item: glock_weapon
node: 10
position:
  - 3
  - 0
---
item: ak47_weapon
node: 11
position:
  - 5
  - 1
---
position:
  - 3
  - 2
item: awp_weapon
node: 12
---
node: 13
item: T_spawn
position:
  - 0
  - 0
---
node: 14
position:
  - 1
  - 0
item: T_spawn
---
item: C_spawn
node: 15
position:
  - 0
  - 3
---
item: C_spawn
node: 16
position:
  - 4
  - 2