width: 13
height: 9
---
item: base_aztec
position:
  - 11
  - 1
---
item: base_aztec
position:
  - 11
  - 2
---
item: base_aztec
position:
  - 11
  - 4
---
item: base_aztec
position:
  - 11
  - 3
---
item: base_aztec
position:
  - 11
  - 5
---
item: base_aztec
position:
  - 11
  - 6
---
item: base_aztec
position:
  - 11
  - 7
---
item: base_aztec
position:
  - 10
  - 7
---
item: base_aztec
position:
  - 9
  - 7
---
item: base_aztec
position:
  - 7
  - 7
---
item: base_aztec
position:
  - 8
  - 7
---
item: base_aztec
position:
  - 6
  - 7
---
item: base_aztec
position:
  - 5
  - 7
---
item: base_aztec
position:
  - 4
  - 7
---
item: base_aztec
position:
  - 3
  - 7
---
item: base_aztec
position:
  - 2
  - 7
---
item: base_aztec
position:
  - 1
  - 7
---
item: base_aztec
position:
  - 1
  - 6
---
item: base_aztec
position:
  - 1
  - 5
---
item: base_aztec
position:
  - 1
  - 4
---
item: base_aztec
position:
  - 1
  - 3
---
item: base_aztec
position:
  - 1
  - 2
---
item: base_aztec
position:
  - 1
  - 1
---
item: base_aztec
position:
  - 2
  - 1
---
item: base_aztec
position:
  - 3
  - 1
---
item: base_aztec
position:
  - 4
  - 1
---
item: base_aztec
position:
  - 5
  - 1
---
item: base_aztec
position:
  - 6
  - 1
---
item: base_aztec
position:
  - 7
  - 1
---
item: base_aztec
position:
  - 8
  - 1
---
item: base_aztec
position:
  - 9
  - 1
---
item: base_aztec
position:
  - 10
  - 1
---
item: base_aztec
position:
  - 2
  - 2
---
item: base_aztec
position:
  - 4
  - 2
---
item: base_aztec
position:
  - 3
  - 2
---
item: base_aztec
position:
  - 3
  - 3
---
item: base_aztec
position:
  - 2
  - 3
---
item: base_aztec
position:
  - 4
  - 3
---
item: base_aztec
position:
  - 4
  - 4
---
item: base_aztec
position:
  - 3
  - 4
---
item: base_aztec
position:
  - 2
  - 4
---
item: base_aztec
position:
  - 2
  - 5
---
item: base_aztec
position:
  - 3
  - 5
---
item: base_aztec
position:
  - 4
  - 5
---
item: base_aztec
position:
  - 4
  - 6
---
item: base_aztec
position:
  - 3
  - 6
---
item: base_aztec
position:
  - 2
  - 6
---
item: base_aztec
position:
  - 5
  - 6
---
item: base_aztec
position:
  - 5
  - 5
---
item: base_aztec
position:
  - 5
  - 4
---
item: base_aztec
position:
  - 5
  - 3
---
item: base_aztec
position:
  - 5
  - 2
---
item: base_aztec
position:
  - 6
  - 2
---
item: base_aztec
position:
  - 6
  - 3
---
item: base_aztec
position:
  - 6
  - 4
---
item: base_aztec
position:
  - 6
  - 5
---
item: base_aztec
position:
  - 6
  - 6
---
item: base_aztec
position:
  - 7
  - 6
---
item: base_aztec
position:
  - 7
  - 5
---
item: base_aztec
position:
  - 7
  - 4
---
item: base_aztec
position:
  - 7
  - 3
---
item: base_aztec
position:
  - 7
  - 2
---
item: base_aztec
position:
  - 8
  - 2
---
item: base_aztec
position:
  - 8
  - 3
---
item: base_aztec
position:
  - 8
  - 5
---
item: base_aztec
position:
  - 8
  - 4
---
item: base_aztec
position:
  - 8
  - 6
---
item: base_aztec
position:
  - 9
  - 6
---
item: base_aztec
position:
  - 9
  - 5
---
item: base_aztec
position:
  - 9
  - 4
---
item: base_aztec
position:
  - 9
  - 3
---
item: base_aztec
position:
  - 9
  - 2
---
item: base_aztec
position:
  - 10
  - 2
---
item: base_aztec
position:
  - 10
  - 3
---
item: base_aztec
position:
  - 10
  - 4
---
item: base_aztec
position:
  - 10
  - 5
---
item: base_aztec
position:
  - 10
  - 6
---
item: box_black
position:
  - 12
  - 8
---
item: box_black
position:
  - 12
  - 7
---
item: box_black
position:
  - 12
  - 6
---
item: box_black
position:
  - 12
  - 5
---
item: box_black
position:
  - 12
  - 4
---
item: box_black
position:
  - 12
  - 3
---
item: box_black
position:
  - 12
  - 2
---
item: box_black
position:
  - 12
  - 1
---
item: box_black
position:
  - 12
  - 0
---
item: box_black
position:
  - 11
  - 8
---
item: box_black
position:
  - 11
  - 0
---
item: box_black
position:
  - 10
  - 8
---
item: box_black
position:
  - 10
  - 0
---
item: box_black
position:
  - 9
  - 8
---
item: box_black
position:
  - 9
  - 0
---
item: box_black
position:
  - 8
  - 8
---
item: box_black
position:
  - 8
  - 0
---
item: box_black
position:
  - 7
  - 8
---
item: box_black
position:
  - 7
  - 0
---
item: box_black
position:
  - 6
  - 8
---
item: box_black
position:
  - 6
  - 0
---
item: box_black
position:
  - 5
  - 8
---
item: box_black
position:
  - 5
  - 0
---
item: box_black
position:
  - 4
  - 8
---
item: box_black
position:
  - 4
  - 0
---
item: box_black
position:
  - 3
  - 8
---
item: box_black
position:
  - 3
  - 0
---
item: box_black
position:
  - 2
  - 8
---
item: box_black
position:
  - 2
  - 0
---
item: box_black
position:
  - 1
  - 8
---
item: box_black
position:
  - 1
  - 0
---
item: box_black
position:
  - 0
  - 8
---
item: box_black
position:
  - 0
  - 7
---
item: box_black
position:
  - 0
  - 6
---
item: box_black
position:
  - 0
  - 5
---
item: box_black
position:
  - 0
  - 4
---
item: box_black
position:
  - 0
  - 3
---
item: box_black
position:
  - 0
  - 2
---
item: box_black
position:
  - 0
  - 1
---
item: box_black
position:
  - 0
  - 0
---
item: C_spawn
position:
  - 2
  - 6
---
item: C_spawn
position:
  - 2
  - 5
---
item: C_spawn
position:
  - 2
  - 4
---
item: C_spawn
position:
  - 2
  - 3
---
item: C_spawn
position:
  - 2
  - 2
---
item: T_spawn
position:
  - 10
  - 6
---
item: T_spawn
position:
  - 10
  - 5
---
item: T_spawn
position:
  - 10
  - 4
---
item: T_spawn
position:
  - 10
  - 3
---
item: T_spawn
position:
  - 10
  - 2
---
Resized: 1