node: 0
item: glock_m
position:
  - 357
  - 226
rate: 1
automatic: false
frequency: 0
damage: 15
accuracy: 50
distance_penalty: 5
price: 50
---
node: 1
item: ak47_m
position:
  - 457
  - 199
rate: 3
automatic: true
frequency: 0.4
damage: 10
accuracy: 100
distance_penalty: 5
price: 10
---
node: 2
item: awp_m
position:
  - 393
  - 284
rate: 1
automatic: false
frequency: 0
damage: 50
accuracy: 100
distance_penalty: 0
price: 500