width: 3
height: 2
---
node: 0
item: base_aztec
position:
  - 2
  - 0
---
node: 1
item: base_inferno
position:
  - 1
  - 1
---
node: 2
item: base_inferno
position:
  - 0
  - 1
---
node: 3
item: base_aztec
position:
  - 1
  - 0
---
node: 4
item: base_aztec
position:
  - 0
  - 0
---
node: 0
item: box_black
position:
  - 1
  - 1
---
node: 1
item: box_brown
position:
  - 0
  - 0
---
node: 2
item: box_brown
position:
  - 0
  - 1
---
node: 3
item: glock_weapon
position:
  - 1
  - 0