node: 0
item: glock
position:
  - 303
  - 279
---
node: 1
item: m3
position:
  - 516
  - 234
---
node: 2
item: cruz
position:
  - 491
  - 325
---
node: 3
item: awp
position:
  - 459
  - 301
---
node: 4
item: awp
position:
  - 455
  - 292
---
node: 5
item: cofre
position:
  - 577
  - 288
---
node: 6
item: ""
position:
  - 478
  - 300
---
node: 7
item: ""
position:
  - 589
  - 329
---
node: 8
item: ""
position:
  - 879
  - 443
