width: 3
height: 3
---
node: 0
item: base_inferno
position:
  - 2
  - 1
---
node: 1
item: base_dust
position:
  - 0
  - 0
---
node: 2
item: base_dust
position:
  - 1
  - 0
---
node: 3
item: base_inferno
position:
  - 0
  - 1
---
node: 4
item: base_inferno
position:
  - 1
  - 1
---
node: 5
item: base_aztec
position:
  - 0
  - 2
---
node: 6
item: base_aztec
position:
  - 1
  - 2