node: 0
item: dust
position:
  - 568
  - 872
---
node: 1
item: dust
position:
  - 504
  - 872
---
node: 2
item: dust
position:
  - 376
  - 259
---
node: 3
item: awp_m
position:
  - 613
  - 572
---
node: 4
item: m3_m
position:
  - 598
  - 306
---
node: 5
item: ak47_m
position:
  - 426
  - 564
---
node: 6
item: glock_m
position:
  - 494
  - 326
---
node: 7
item: box_metal
position:
  - 635
  - 408
---
node: 8
item: box_wood_metal
position:
  - 504
  - 432
---
node: 9
item: box_wood
position:
  - 563
  - 481
---
node: 10
item: box_black
position:
  - 576
  - 349
---
node: 11
item: box_brown
position:
  - 451
  - 380
---
node: 12
item: default_dust
position:
  - 376
  - 259