node: 0
item: awp
position:
  - 297
  - 261
---
node: 1
item: awp
position:
  - 544
  - 214
---
node: 2
item: awp
position:
  - 402
  - 187
---
node: 3
item: m3
position:
  - 429
  - 229
---
node: 4
item: ak47
position:
  - 351
  - 245
---
node: 5
item: glock
position:
  - 468
  - 192
---
node: 6
item: cruz
position:
  - 430
  - 280
---
node: 7
item: cruz
position:
  - 369
  - 278
---
node: 8
item: cruz
position:
  - 443
  - 317
---
node: 9
item: cofre
position:
  - 460
  - 279
---
node: 10
item: canion
position:
  - 388
  - 332
---
node: 11
item: barril
position:
  - 356
  - 183
---
node: 12
item: balas
position:
  - 449
  - 228
---
node: 13
item: ametralladora
position:
  - 315
  - 237
---
node: 14
item: cruz
position:
  - 369
  - 278
---
node: 15
item: cruz
position:
  - 443
  - 317
---
node: 16
item: cofre
position:
  - 460
  - 279
---
node: 17
item: canion
position:
  - 473
  - 257
---
node: 18
item: barril
position:
  - 356
  - 183
---
node: 19
item: balas
position:
  - 449
  - 228
---
node: 20
item: ametralladora
position:
  - 315
  - 237
---
node: 21
item: ametralladora
position:
  - 315
  - 237
---
node: 22
item: balas
position:
  - 449
  - 228
---
node: 23
item: barril
position:
  - 475
  - 124
---
node: 24
item: canion
position:
  - 473
  - 257
---
node: 25
item: cofre
position:
  - 460
  - 279
---
node: 26
item: cruz
position:
  - 443
  - 317
---
node: 27
item: cruz
position:
  - 369
  - 278
---
node: 28
item: balas
position:
  - 214
  - 137