height: 5
width: 9
---
item: base_dust
position:
  - 0
  - 0
node: 0
---
position:
  - 1
  - 0
item: base_dust
node: 1
---
item: base_inferno
position:
  - 0
  - 1
node: 2
---
node: 3
item: base_inferno
position:
  - 1
  - 1
---
node: 4
position:
  - 0
  - 2
item: base_aztec
---
position:
  - 1
  - 2
node: 5
item: base_aztec
---
position:
  - 4
  - 0
item: base_aztec
node: 6
---
node: 7
position:
  - 3
  - 0
item: base_aztec
---
node: 8
position:
  - 7
  - 0
item: base_aztec
---
item: base_aztec
position:
  - 1
  - 0
node: 9
---
node: 10
position:
  - 2
  - 0
item: base_aztec
---
item: base_aztec
node: 11
position:
  - 6
  - 0
---
item: base_aztec
node: 12
position:
  - 4
  - 1
---
position:
  - 8
  - 0
node: 13
item: base_aztec
---
item: base_aztec
node: 14
position:
  - 5
  - 0
---
position:
  - 6
  - 1
item: base_aztec
node: 15
---
node: 16
item: base_aztec
position:
  - 7
  - 1
---
node: 17
item: base_aztec
position:
  - 8
  - 1
---
node: 18
item: base_aztec
position:
  - 2
  - 1
---
item: base_aztec
position:
  - 5
  - 1
node: 19
---
position:
  - 3
  - 1
node: 20
item: base_aztec
---
item: base_aztec
position:
  - 1
  - 1
node: 21
---
position:
  - 0
  - 1
node: 22
item: base_aztec
---
node: 23
position:
  - 8
  - 2
item: base_aztec
---
item: base_aztec
node: 24
position:
  - 8
  - 3
---
item: base_aztec
position:
  - 8
  - 4
node: 25
---
position:
  - 0
  - 2
item: base_aztec
node: 26
---
node: 27
item: base_aztec
position:
  - 0
  - 3
---
node: 28
position:
  - 0
  - 4
item: base_aztec
---
node: 29
position:
  - 1
  - 4
item: base_aztec
---
position:
  - 2
  - 4
node: 30
item: base_inferno
---
item: base_aztec
position:
  - 3
  - 4
node: 31
---
node: 32
item: base_aztec
position:
  - 4
  - 4
---
node: 33
item: base_aztec
position:
  - 5
  - 4
---
position:
  - 6
  - 4
item: base_aztec
node: 34
---
position:
  - 7
  - 4
node: 35
item: base_aztec
---
item: base_aztec
position:
  - 1
  - 2
node: 36
---
position:
  - 1
  - 3
node: 37
item: base_aztec
---
position:
  - 2
  - 2
item: base_aztec
node: 38
---
node: 39
position:
  - 2
  - 3
item: base_aztec
---
position:
  - 3
  - 2
item: base_aztec
node: 40
---
node: 41
position:
  - 3
  - 3
item: base_aztec
---
item: base_aztec
position:
  - 4
  - 2
node: 42
---
item: base_aztec
position:
  - 4
  - 3
node: 43
---
item: base_aztec
position:
  - 5
  - 3
node: 44
---
item: base_aztec
node: 45
position:
  - 5
  - 2
---
position:
  - 6
  - 3
node: 46
item: base_aztec
---
position:
  - 6
  - 2
item: base_aztec
node: 47
---
item: base_aztec
node: 48
position:
  - 7
  - 2
---
node: 49
position:
  - 7
  - 3
item: base_aztec
---
position:
  - 0
  - 0
node: 0
item: T_spawn
---
item: T_spawn
position:
  - 0
  - 1
node: 1
---
item: T_spawn
node: 2
position:
  - 0
  - 2
---
position:
  - 0
  - 3
node: 3
item: T_spawn
---
node: 4
position:
  - 0
  - 4
item: T_spawn
---
node: 5
position:
  - 8
  - 0
item: C_spawn
---
position:
  - 8
  - 1
item: C_spawn
node: 6
---
position:
  - 8
  - 2
node: 7
item: C_spawn
---
position:
  - 8
  - 3
item: C_spawn
node: 8
---
node: 9
item: C_spawn
position:
  - 8
  - 4