node: 0
item: aztec
position:
  - 63
  - 385
---
node: 1
item: inferno
position:
  - 127
  - 385
---
node: 2
item: dust
position:
  - 63
  - 1
---
node: 3
item: default_dust
position:
  - 56
  - 3
---
node: 4
item: base_dust
position:
  - 56
  - 3
---
node: 5
item: base_inferno
position:
  - 120
  - 387
---
node: 6
item: base_aztec
position:
  - 56
  - 387